stages:
  disambig_const:
    cmd: jupyter nbconvert --to notebook --execute --inplace 10.01-disambig_constiutents.ipynb
    deps:
    - ../data/di-morphosyntax.csv
    - 10.01-disambig_constiutents.ipynb
    outs:
    - ../data/disambig_mr.csv
  train_alpha:
    cmd: nbconvert --to notebook --execute --inplace 10.02-classify-mr.ipynb
    deps:
    - ../data/di-morphosyntax.csv    
    outs:
    - ../data/models/morphen-alpha-220802-0840/
    - ../data/10.02-word-split.json
  tencent-extract:
    cmd: jupyter nbconvert --to notebook --execute --inplace 10.10-tencent-extract.ipynb
    deps:
    - ../data/di-morphosyntax.csv    
    outs:
    - ../data/verb_morpho.csv
    - ../data/verb_morpho_emb.txt
  tencent-extract-500k:
    cmd: jupyter nbconvert --to notebook --execute --inplace 10.10.1-tencent-extract-500k.ipynb    
    outs:
    - ../data/tencent_d200_500k.bin  
  tencent-lda-char:
    cmd: jupyter nbconvert --to notebook --execute --inplace 10.12-tencent-lda-char.ipynb
    deps:
    - ../data/verb_morpho.csv
    - ../data/verb_morpho_emb.txt
    - ../data/10.02-word-split.json
    outs:
    - ../data/tencent-mr-lda-char.split.json
    - ../data/tencent-mr-lda-char.joblib
  tencent-lda-word:
    cmd: jupyter nbconvert --to notebook --execute --inplace 10.14-tencent-lda-word.ipynb
    deps:
    - ../data/verb_morpho.csv
    - ../data/verb_morpho_emb.txt
    - ../data/10.02-word-split.json
    outs:
    - ../data/tencent-mr-lda-word.split.json
    - ../data/tencent-mr-lda-word.joblib
  tencent-delta:
    cmd: jupyter nbconvert --to notebook --execute --inplace 20.01-decompo-vec.ipynb
    outs:
    - ../data/delta_tenc_d200_biwords.bin    

